### ISSUE TITLE
Support new todo items on a todo list.

### ISSUE THREAD

**Issue by TrailHacker** [ymvrali/ToDoMVC#10]
We already have the javascript implementation to create a new todo item. However, it simply renders a new item in the table. 

We now need to support the logic to _save_ the `TodoItem` at the server (when `item.Id = 0`). Once the items has been added to the database, we need to send the new `Id` back down to the client so that the javascript `ViewModel` knows about the new `Id`. This is required in case the user changes the text of the new todo item after it's been saved.

Things to do at the `TodoItemsController.Save(TodoItem item)` method:

- [x] Check for `item.Id == 0`, and use the `_context.TodoItems.Add()` method.
- [x] Return the `Id` to the client with `return Ok(item.Id)`.

Things to do at the `ViewModel.postData(...)` method.
- [x] Store the new `id` with the client-side `TodoItem.id` property.

**Comment by TrailHacker** [comment]
Fixed with pr #11.
